spring:
  profiles:
    active: ${PROFILE}

url: ${URL}
bcb-url: https://api.bcb.gov.br/dados/serie/

logging:
  level:
    com:
      installments:
        calculator:
          client:
            CalculatorClient: DEBUG
            BcbClient: DEBUG